# Generated by Django 4.1.4 on 2022-12-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_active_filter_one_time_zone_and_more'),
        ('users', '0004_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='сompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='сompany'),
        ),
    ]
