# Generated by Django 4.1.4 on 2022-12-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT HAVE IN DB', 'NOT HAVE IN DB'), ('USER BAN', 'USER BAN'), ('DEVICE BANNED', 'DEVICE BANNED'), ('RETRY USER', 'RETRY USER'), ('STOP TIME ZONE', 'STOP TIME ZONE'), ('STOP MCHECKER', 'STOP MCHECKER')], max_length=20, verbose_name='status'),
        ),
    ]
