# Generated by Django 4.1.4 on 2022-12-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'companies', 'verbose_name_plural': 'company'},
        ),
    ]
