# Generated by Django 4.1.4 on 2022-12-30 10:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_active_filter_one_time_zone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('logs', django.db.models.manager.Manager()),
            ],
        ),
    ]
