# Generated by Django 4.1.4 on 2022-12-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_rename_country_country_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creates_at', models.DateTimeField(auto_now_add=True, verbose_name='creates_at')),
                ('ip', models.CharField(max_length=100, verbose_name='ip')),
                ('getz_user', models.CharField(max_length=100, verbose_name='getz')),
                ('domen', models.CharField(max_length=255, verbose_name='domen')),
                ('packege_id', models.CharField(max_length=255, verbose_name='packege_id')),
                ('usser_id', models.CharField(max_length=255, verbose_name='usser_id')),
                ('utm_medium', models.CharField(default='organic', max_length=255, verbose_name='usser_id')),
                ('user_agent', models.CharField(max_length=255, verbose_name='user_agent')),
                ('status', models.CharField(blank=True, choices=[('USER BAN', 'USER BAN'), ('RETRY USER', 'RETRY USER'), ('VIRTUAL DEVICE', 'VIRTUAL DEVICE')], max_length=20, verbose_name='status')),
                ('filter_one_time_zone', models.CharField(blank=True, choices=[('Stop TimeZone', 'Stop TimeZone'), ('SUCCESSFUL', 'SUCCESSFUL')], max_length=20, verbose_name='filter_one_time_zone')),
                ('filter_two_cheker', models.CharField(choices=[('Stop Mchecker', 'Stop Mchecker'), ('SUCCESSFUL', 'SUCCESSFUL')], max_length=20, verbose_name='filter_two_cheker')),
                ('final', models.BooleanField(verbose_name='final')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country', verbose_name='county')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'logs',
                'verbose_name_plural': 'log',
            },
        ),
    ]
