# Generated by Django 4.1.4 on 2022-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filter_two_cheker',
            field=models.CharField(blank=True, choices=[('Stop Mchecker', 'Stop Mchecker'), ('SUCCESSFUL', 'SUCCESSFUL')], max_length=20, verbose_name='filter_two_cheker'),
        ),
    ]
