# Generated by Django 4.1.4 on 2022-12-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_getr_alter_log_utm_medium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='getr',
            new_name='getr_user',
        ),
    ]
