# Generated by Django 4.1.4 on 2022-12-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_status'),
        ('logs', '0004_rename_getr_log_getr_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='log',
            name='final',
            field=models.BooleanField(default=False, verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='ip'),
        ),
    ]
