# Generated by Django 4.1.4 on 2022-12-26 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_log_user_log_client_alter_log_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='creates_at',
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT HAVE IN DB', 'NOT HAVE IN DB'), ('USER BAN', 'USER BAN'), ('DEVICE BANNED', 'DEVICE BANNED'), ('RETRY USER', 'RETRY USER'), ('VIRTUAL DEVICE', 'VIRTUAL DEVICE')], max_length=20, verbose_name='status'),
        ),
    ]
