# Generated by Django 4.1.4 on 2022-12-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_rename_country_country_name'),
        ('logs', '0006_remove_log_creates_at_log_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='county',
        ),
        migrations.AddField(
            model_name='log',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country', verbose_name='country'),
        ),
    ]
