# Generated by Django 4.1.4 on 2022-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT HAVE IN DB', 'NOT HAVE IN DB'), ('USER BAN', 'USER BAN'), ('DEVICE BANNED', 'DEVICE BANNED'), ('RETRY USER', 'RETRY USER'), ('VIRTUAL DEVICE', 'VIRTUAL DEVICE')], max_length=20, verbose_name='status'),
        ),
    ]
