# Generated by Django 4.1.4 on 2022-12-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_client_status'),
        ('countries', '0002_rename_country_country_name'),
        ('companies', '0005_alter_company_managers'),
        ('logs', '0010_log_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='log',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='companies.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='log',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='countries.country', verbose_name='country'),
        ),
    ]
