# Generated by Django 4.1.4 on 2023-01-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_log_client_alter_log_company_alter_log_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='detail_status',
            field=models.TextField(blank=True, verbose_name='detail_status'),
        ),
    ]
