# Generated by Django 4.1.4 on 2023-01-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_log_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='timezone_from_header',
            field=models.CharField(blank=True, max_length=100, verbose_name='timezone_from_header'),
        ),
    ]
