# Generated by Django 4.1.4 on 2023-01-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_log_timezone_from_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filter_one_time_zone',
            field=models.CharField(blank=True, choices=[('Stop TimeZone', 'Stop TimeZone'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FILTER OFF', 'FILTER OFF'), ('FILTER NOT STARTED', 'FILTER NOT STARTED')], max_length=20, verbose_name='filter_one_time_zone'),
        ),
        migrations.AlterField(
            model_name='log',
            name='filter_two_cheker',
            field=models.CharField(blank=True, choices=[('Stop Mchecker', 'Stop Mchecker'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FILTER OFF', 'FILTER OFF'), ('FILTER NOT STARTED', 'FILTER NOT STARTED')], max_length=20, verbose_name='filter_two_cheker'),
        ),
    ]
