# Generated by Django 4.1.4 on 2023-01-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_alter_log_filter_one_time_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='url',
            field=models.TextField(blank=True, verbose_name='url'),
        ),
    ]
